


<ul>
    <li>Name   : <?= $block->escapeHtml($block->getName()) ?></li>
    <li>Email  :  <?= $block->escapeHtml($block->getCustomer()->getEmail()) ?></li>
    <li>Phone  :  <?= $block->escapeHtml($block->getTelephoneCustomer()) ?></li>
    <li>Avatar:
    <span class="customer-name"
          role="link"
          tabindex="0"
          data-mage-init='{"dropdown":{}}'
          data-toggle="dropdown"
          data-trigger-keypress-button="true"
          data-bind="scope: 'customer'">
            <img data-bind="attr:{src: customer().avatar}" width="30px" height="25px" class="avatar-header-links action switch" data-action="customer-menu-toggle" tabindex="-1"/>
        </span>
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "customer": {
                            "component": "Magento_Customer/js/view/customer"
                        }
                    }
                }
            }
        }
    </script>

    </li>
</ul>

