<h1>Total Request Today</h1>
<div style="display: flex">
    <div>Numbers of module installed in Magneto : <strong><?php echo $block->modulesList(); ?></strong></div>
    <div style="margin-left: 350px">
        <ul>
            <li>Numbers of Customers :<strong><?php echo $block->getCustomerGroups(); ?> </strong></li>
            <li>Numbers of Products  :<strong> <?php echo $block->getProducts(); ?></strong></li>
            <li>Numbers of Invoices    : <strong> <?php echo $block->getCountInvoicesForOrder(2); ?></strong></li>
        </ul>
    </div>
</div>











